### ISSUE TITLE
The diagrams in the book are unreadable in dark mode

### ISSUE THREAD

**Issue by Arnavion** [time-rs/book#1]
https://time-rs.github.io/book/api/format-description.html

![image](https://user-images.githubusercontent.com/1096010/136863048-4915832d-b66e-4be6-817d-e29e4c1c6831.png)

`background-color: white; padding: 1em;` in https://github.com/time-rs/time-rs.github.io/blob/3a35fed338f8166cb8211609e09f978be5dd16dc/book/css/general.css#L95 makes it better.

**Comment by jhpratt** [comment]
Could you please provide your browser and operating system (both including the version)? Additionally, what theme is this?

I ask because there is CSS that _should_ invert the diagrams (such that they're white) on dark themes. It works on my machine but I never tried it on anything else. If there's something in the CSS I missed then I can definitely make the necessary adjustments.

**Comment by Arnavion** [comment]
>adding in `.light.no-js` under `prefers-color-scheme: dark` would force the themes to be like this even if the user wanted a light theme.

The pre-defined theme already does this (the variables.css link in my comment), so why is this a problem?
